### PR TITLE
Add setUnlocal to ItemEE constructor

### PR DESCRIPTION
**Pull request by yesimwearingpants**
This should also work for hasSubTypes

### CODE REVIEW

**Comment by pahimar** [comment]
What's the point of this? Appears to be more about style than anything

**Comment by yesimwearingpants** [comment]
Half about styling, but it does make it faster to add new Items.

**Comment by simon816** [comment]
This isn't even valid Java, you should put the `Names.Items.*` in the `super()` call method.
and `public ItemEE(name)` should be `public ItemEE(String name)`

**Comment by yesimwearingpants** [comment]
Sorry about that I was Doing the same thing with my own mod (correctly), And Noticed It would be easy to apply elsewhere. I didn't see the error because EE3 is not added to my project yet.

**Comment by pahimar** [comment]
Not interested in code style prs

**Pull request closed without merging**
