### PR TITLE
Render Tome of Alchemical Knowledge on top of the Research Station

### PR DESCRIPTION
**Pull request by ganymedes01**
I think it looks better this way. Take this as a suggestion :3

screen shot 2015-05-15 at 17 35 30

screen shot 2015-05-15 at 17 40 31

### CODE REVIEW

**Comment by WolfieWaffle** [comment]
I'm just a random person, but anyways, I like it! It makes it look less like a random table and more like a mystical magical table that you use for... well... research.

**Comment by reapersremorse** [comment]
Pahimar needs modelers, if he added this then he would need someone to
modle it for him.

**Comment by WolfieWaffle** [comment]
If I'm correct, ganymedes already has, Pahimar just needs to add it.

**Comment by ganymedes01** [comment]
No one needs to model anything...
This isn't just a request, the code for it has already been already written by me ^^

**Comment by pahimar** [comment]
Does the book render appropriately based on the rotation of the Research Station?

**Comment by ganymedes01** [comment]
Since the book is pretty much centred, only slightly crooked, and the table is symmetric, I didn't think that that was necessary. Would you like it to?

**Comment by pahimar** [comment]
Lets give it a try :)

**Pull request merged**
