### PR TITLE
Simplifications, Stability and Strictness.

### PR DESCRIPTION
**Pull request by tekacs**
1) Simplifications
   A bunch of expressions have been hugely simplified.
   There's _lots_ more potential stock, but I've tried to minimise the
   number of files I've touched to the ones needed for functionality
   changes for now.

2) Stability is much improved. No more GUI glitches.
   There's a bit more to be done by:
   a) Finishing the migration to one-way dataflow (for now) for EMC in
   the Transmutation Tablet to make sync perfect.
   b) Scroll wheel extract needs fixing (which should fix any remaining
   inventory glitches too).
   d) Fixing tiles other than the Transmutation Tablet - changes are
   mostly more of the same but again, I tried to minimise files/lines touched for now.

3) Strictness
   Reduce duplication and make server/client proxy behaviour explicit
   and safe (e.g. ProgressMessage/LinearProgressHandler/ProgressType).
   The other Tile Entities that use updateProgressBar need to be
   updated to use these, too.

### CODE REVIEW

**Comment by tekacs** [comment]
Continuing CI status on this branch: [Build Status](https://drone.io/github.com/tekacs/Equivalent-Exchange-3/latest)

**Comment by pahimar** [comment]
Still trying to find time to properly review this. Why the move to a this LinearProgressHandler? I'd like to understand your reasoning

**Comment by tekacs** [comment]
Three reasons:

* That logic is duplicated many times, so having a class or function for it is natural.
* There were minor encode/decode/ordering bugs in some of the original implementation - encode/decode is now implemented exactly once and need only be tested exactly once.
* Symmetry between client and server is now 'forced' - due to the enum generic it's hard to add a server send without a client receive and easy to search the code for references to a message.

To be clear, this could have been done without the generic parameter, but then the class' code would need to be copy/pasted once for each TileEntity which used it, once again giving us half a dozen sites to update if bugs show up.

**Comment by tekacs** [comment]
Oh and the inverted/linear stuff is just it automatically generating an inverted ID to better prevent the server and client from falling out of sync when sending continuation packets and using an inverted/non-inverted packet order to receive them.

(i.e. to send the two halves of an int on channel 3, sends:

~3 -> 1st half
3  -> 2nd half

Rather than the previous:
3 -> 1st half
3 -> 2nd half

Which would fall out of sync indefinitely after a race condition on the server, where the new approach will only at worst mix packets during the race.)

**Pull request closed without merging**
